### ISSUE TITLE
Version 1.2.2 causes error in Angular DI: No provider for CookieOptions 

### ISSUE THREAD

**Issue by macolo** [salemdar/angular2-cookies#10]
We didn't yet have the time to investigate further but going back to 1.2.1 definitely solves the issue.

If we find out more we post an update here.

```
npm ls | grep angular
├── @angular/common@2.0.0-rc.1
├── @angular/compiler@2.0.0-rc.1
├── @angular/core@2.0.0-rc.1
├── @angular/http@2.0.0-rc.1
├── @angular/platform-browser@2.0.0-rc.1
├── @angular/platform-browser-dynamic@2.0.0-rc.1
├── @angular/router-deprecated@2.0.0-rc.1
├─┬ angular2-cookie@1.2.1
```

**Comment by salemdar** [comment]
Hey @macolo 
Thanks for your feedback. I am inspecting the issue. It would be really helpful if you could post your bootstrap function and custom cookie options class.

**Comment by macolo** [comment]
Thank you for your help!

Here you go: https://gist.github.com/macolo/b37f0d859c863172e17359e76c11ef94

**Comment by snehasis** [comment]
Any update on the Issue ? How to use this On the Application ?

**Comment by salemdar** [comment]
Try to use the latest version. And there is a huge getting started section on the readme file.

**Comment by brendanalexdr** [comment]
I'm getting this error now when I do AOT compilation with angular-cli.  Works find with a non-AOT  (JiT) build.

**Comment by NgxDev** [comment]
Same here, getting the error when building with `--aot`

**Comment by bradseefeld** [comment]
Getting the same with angular 2.4.2, ng-cli 1.0.0-beta24 and angular-cookies 1.2.6.

```
Error: No provider for CookieOptions!
```

@salemdar, can we re-open this?

The only way I can get it to work is if I import like this:
```
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { CookieService, BaseCookieOptions, CookieOptions } from "angular2-cookie/core";

export function cookieServiceFactory(options: CookieOptions) {
  return new CookieService(options);
}

@NgModule({
  imports: [
    CommonModule,
    ...
 ],
  providers: [
    { provide: CookieOptions, useClass: BaseCookieOptions },
    { provide: CookieService, useFactory: cookieServiceFactory, deps: [CookieOptions] },
    ...
  ]
})
export class MyModule {
}
```

Which basically copies your core file: https://github.com/salemdar/angular2-cookie/blob/master/src/core.ts

I believe the issue is that you are not exposing a module for us to import, and by only recommending we declare the `CookieService` in our modules, DI cant find an implementation for `CookieOptions`. I think if you were to instead have a module that 'provided' both of these for us, we could import that module and be done.

**Comment by bradseefeld** [comment]
Correction... here is my module:
```
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { CookieService, BaseCookieOptions, CookieOptions } from "angular2-cookie/core";

export function cookieServiceFactory() {
  return new CookieService();
}

@NgModule({
  imports: [
    CommonModule,
    ...
 ],
  providers: [
    { provide: CookieService, useFactory: cookieServiceFactory },
    ...
  ]
})
export class MyModule {
}
```

If I try to import the CookieOptions, I get an unknown token error after building for AOT. However, I still think the issue is caused by the fact that a `CookieModule` is not being exposed with the proper things already 'provided' for us to import.

**Comment by ghost** [comment]
Having the same issue. Downgrading to previous version until this is fixed!

**Comment by patrikx3** [comment]
Same error

**Comment by schulzp** [comment]
Still getting the error with angular 2.4.10.

**Comment by ghost** [comment]
Use ngx-cookie instead

**Comment by iravitejakumar** [comment]
I have used ngx-cookie but i still got the following error while iam doing ng serve --eot

Error: No provider for Token COOKIE_OPTIONS!

**Comment by ghost** [comment]
Are you importing the module properly @iravitejakumar ?

**Comment by iravitejakumar** [comment]
Yes @rolandoldengarm  I have imported module properly. I have declared my provider in app.module as follows.
```
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(routes, { useHash: true })
  ],
  providers: [CookieService,{ provide: CookieOptions, useValue: {} }],
  bootstrap: [AppComponent]
})
```

It solved my problem and its working fine now.

**Comment by NgxDev** [comment]
@iravitejakumar 
all I have in my app.module is:
```
import { CookieModule } from 'ngx-cookie';
// ...
imports: [
    CookieModule.forRoot()
]
```
Then, wherever I use it, I have `import { CookieService } from 'ngx-cookie';`
And I also inject it through the constructor, of course `constructor(private cookieService: CookieService) {}`

That's all, no providers. It's working perfect for me.

**Comment by rolandoldengarm** [comment]
@iravitejakumar you are not importing the CookieModule... As I said.

**Comment by bculley** [comment]
I was getting the same error in karma testing and @MrCroft 's answer pointed in the right direction, I was missing the .forRoot() in the app.component.spec.ts file, same as the app.module.ts


```
describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        HttpClientModule,
        CookieModule.forRoot(),
      ],
      declarations: [ ],
      providers: [ ]
    }).compileComponents();
  }));
