### ISSUE TITLE
how to unit test component that reads a cookie

### ISSUE THREAD

**Issue by githublogon** [salemdar/angular2-cookies#11]
First of all thanx for providing this lib.

I try to unit test my component and do the following  "boilerplate" stuff:
(I left out the details of the component)

---

import { CookieService, ANGULAR2_COOKIE_PROVIDERS } from 'angular2-cookie/core';

export function main() {
    describe('component test', () => {

```
    beforeEachProviders(() => [
        ANGULAR2_COOKIE_PROVIDERS,
        CookieService,
    ]);

    beforeEach(doCookie);

    it('test', () => {
        expect(...);
    });

});
```

}

function doCookie() {
    return inject([CookieService], (cookieService: CookieService) => { cookieService.removeAll(); cookieService.put('number', '1'); });
## }

I get an error while running the test:

404: /base/angular2-cookie/core.js

Can you tell why this error occurs? 

Thanx,
Adrian

**Comment by salemdar** [comment]
Hey Adrian,
You need to point the library in your test configurations. You can check the following files as example:

https://github.com/salemdar/angular2-cookie/blob/master/test/services/cookie.service.spec.ts
https://github.com/salemdar/angular2-cookie/blob/master/karma-test-shim.js
https://github.com/salemdar/angular2-cookie/blob/master/karma.conf.js

If your that does not solve your problem, just show me your test configurations and I will try to help.

Best regards,
Samet

**Comment by juanhipo** [comment]
Hello Salensar. Can you help me ?. I have a problem when I run my tests this is what i saw in console

![screenshot_3](https://user-images.githubusercontent.com/39890138/45242130-83ce6880-b2b4-11e8-9afa-c5152ea7115b.png)
