### ISSUE TITLE
Injecting CookieService inside another service

### ISSUE THREAD

**Issue by ritz078** [salemdar/angular2-cookies#12]
Can't get this to work .

``` ts
import {Injectable} from '@angular/core';

import {CookieService} from 'angular2-cookie/core';

@Injectable()
export class SelectedCityService {
  constructor(private _cookie: CookieService) {
  }

  get selectedCity(): Object {
    return this._cookie.getObject('selectedCity');
  }

  set selectedCity(selectedCity: Object) {
    this._cookie.putObject('selectedCity', selectedCity);
  }
}
```

I get a DI error. 
`No provider for CookieService`

**Comment by salemdar** [comment]
Hey @ritz078 

Could you try renaming the methods to `getSelectedCity` and `setSelectedCity` (without spaces).
If that doesn't work, I need to see your SystemJS configurations.

Best regards,
Samet

**Comment by ritz078** [comment]
Using the latest angular-cli with webpack instead of SystemJS.

removed `set` and `get` and changed to `setSelectedCity`. Still getting the same error.

**Comment by salemdar** [comment]
And you don't any errors when you use `CookieService` directly in a component? 
I am updating angular-cli and try to create a test project. I will let you know.

**Comment by ritz078** [comment]
no

**Comment by salemdar** [comment]
Are you adding `CookieService` to you providers list or to `bootstrap()` method?

**Comment by yazeedb** [comment]
That could be it, @ritz078 
`No provider for service` usually means you haven't added that service to your `providers` array. This is because in Angular 2, you can't just inject a service into another class's constructor, it has to be declared in either that class's `providers` array, or a parent class/component's.

Hope that helps
