### ISSUE TITLE
Secure cookie not working. 

### ISSUE THREAD

**Issue by sethdorris** [salemdar/angular2-cookies#13]
How do you set a secure cookie?

When I inspect the cookie in Cookie Inspector it says the cookie is not secure. This is the call. 

`this.cookieService.put("username", username, {secure: true})`

**Comment by owlstack** [comment]
Why was this issue closed? I have the same issue!

**Comment by YuriFontella** [comment]
How did you solve the problem?
When I put {secure: true} it simply does not generate the cookie.

**Comment by sethdorris** [comment]
Hey man,

I can't remember since I'm not working on that project anymore but fairly certain I went to a new library.
