### ISSUE TITLE
install issue with 1.2.2 and angular 2.0.0-rc.5

### ISSUE THREAD

**Issue by ad34** [salemdar/angular2-cookies#14]
Hi,

I have trouble installing v 1.2.2 with angular2 rc5 (with angular cli)

all steps has been performed (npm install, system-config modifications, declaring the provider, importing CookieService)

the Typescript files compiles without any issue but I have this error @app loading in the browser

zone.js:101 GET http://localhost:4200/vendor/angular2-cookie/core 404 (Not Found)

I checked the dist\vendor\angular2-cookie folder and it s here (core.js + other stuff inside)

Find a lot of similar issues while googling so I guess the issue is more related to changes in angular rather than the angular cookie module itself, anyway I post the issue here because other users may experience this issue.

I posted the question to stackoverflow as well http://stackoverflow.com/questions/39268655/importing-angular2-cookie-in-angular2-rc5-project

**Comment by salemdar** [comment]
Answered on SO.
