### ISSUE TITLE
RC6: import `@angular/core/src/facade/lang` causes traceur error

### ISSUE THREAD

**Issue by kephas123** [salemdar/angular2-cookies#15]
- Bug report

Similar to https://github.com/ocombe/ng2-translate/issues/219

**Comment by ocombe** [comment]
yes they removed access to those things in rc6 (they are considered internals apis), anything that is not exported by `@angular/xxx` is now private (you will get the error with `import {getDOM} from '@angular/platform-browser/src/dom/dom_adapter';` as well for example

**Comment by salemdar** [comment]
I am working on a fix at the moment. Thanks for pointing out the issue.
