### ISSUE TITLE
Upgrade to Final from RC5 

### ISSUE THREAD

**Issue by webartistkb** [salemdar/angular2-cookies#18]
Getting these errors:
├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.5 invalid
├── UNMET DEPENDENCY @angular/compiler@2.0.0
├── UNMET DEPENDENCY @angular/core@2.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.5 invalid
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.0.0-rc.5 invalid
├─┬ angular2-cookie@1.2.3 
│ ├── @angular/common@2.0.0 
│ ├── @angular/compiler@2.0.0 
│ ├── @angular/core@2.0.0 
│ ├── @angular/platform-browser@2.0.0 
│ ├── reflect-metadata@0.1.8 
│ ├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
│ └── zone.js@0.6.23 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6 invalid
├── UNMET PEER DEPENDENCY typescript@2.0.0
└── UNMET PEER DEPENDENCY zone.js@0.6.12 invalid

**Comment by salemdar** [comment]
I was on holiday. There's an upgrade coming really soon.

**Comment by salemdar** [comment]
Check the 1.2.4 version.
