### ISSUE TITLE
How to use ANGULAR2_COOKIES_PROVIDERS ?

### ISSUE THREAD

**Issue by no-more** [salemdar/angular2-cookies#2]
Hello,

I'm quite new to angular2, and I don't understand where ANGULAR2_COOKIES_PROVIDERS  comes from and how to use it.
What I want to do is change bootstraping option in order to specify the domain.

Thanks.

**Comment by no-more** [comment]
Just find out there an error in the doc it should be ANGULAR2_COOKIE_PROVIDERS.

**Comment by salemdar** [comment]
@no-more Yes, you are right. I am going to change the documentation once I get to the home. Does your question still stand after your second comment?

**Comment by no-more** [comment]
No you can close this.

Just another question, but it's not related to this. I'm looking for a way to share data cross multiple subdomains without cookies. I would like to avoid the overhead of the cookie but can't find how to. It seems there used to be a way to do it with local storage and iframes, but it looks like it's not supported anymore on safari.

Thanks.
And it's working great.

**Comment by salemdar** [comment]
Solved wıth the v1.1.1
