### ISSUE TITLE
Connect angular2-cookie to webpack-angular2

### ISSUE THREAD

**Issue by hameltomor** [salemdar/angular2-cookies#22]
Hi! How can I set path for angular2-cookie using [webpack-angular2](https://github.com/AngularClass/angular2-webpack-starter)?

**Comment by salemdar** [comment]
I will update the readme file with the next release.

**Comment by salemdar** [comment]
Added with v1.2.5.

**Comment by Splaktar** [comment]
@salemdar The README updates for v1.2.5 don't appear to be up to date with angular-cli beta.15+ (current is beta.18) which is based on webpack. They still refer to SystemJS and `angular-cli-build.js` which doesn't exist anymore.

Please take a look at the following links for more details:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14
https://angular-maps.com/docs/getting-started.html

**Comment by talmog** [comment]
`/src/vendor.browser.ts` doesn't exist anymore in angularClass webpack project...
Can you please advice where to declare the dependency? I found a place in webpack.dev.js under "vendors" but not in webpack.prod.js
Thanks!
