### ISSUE TITLE
Removing a cookie or getting a key that does not exist creates a cookie

### ISSUE THREAD

**Issue by cocoviper** [salemdar/angular2-cookies#23]
Hi

I found that when getting a cookie that does not exist , a cookie is created with a string value "undefined" .

I attempted to remove it,but found out that a removed cookie is set to "undefined" also instead of being removed.

I'm using Angular Final with version 1.2.4 of your tool

**Comment by salemdar** [comment]
I will investigate this issue asap and release a new version with the fix. Thanks for letting me know.

**Comment by salemdar** [comment]
I could not reproduce the issue with Chrome or Firefox.
