### ISSUE TITLE
Get all attributes of object Cookie

### ISSUE THREAD

**Issue by fernandocode** [salemdar/angular2-cookies#26]
It is possible to get value `expires`or `create` from a cookie with this library? 
- If yes. How should this be done? 
- If not. Is possible add this functionality the this library?

This information of print for example:

> ![cookie](https://cloud.githubusercontent.com/assets/3801304/19492914/6ebc78e6-9557-11e6-8c52-c162ebc4fc1f.png)

**I noticed is only possible with the library to get the value of the `Content`attribute of the print.**

**Comment by salemdar** [comment]
http://stackoverflow.com/questions/1532193/reading-cookie-expiration-date

I don't think that is possible without dirty hacks.
