### ISSUE TITLE
Cookie core not found

### ISSUE THREAD

**Issue by NablaT** [salemdar/angular2-cookies#3]
Hello, 

I have followed the steps in the documentation but I still have a problem of import. 
I had angular2-cookie in my node modules: 
![image](https://cloud.githubusercontent.com/assets/3800025/14951756/a882dca4-105b-11e6-94e0-1aac095e750a.png)

Then I inject angular2-cookie: 
![image](https://cloud.githubusercontent.com/assets/3800025/14951671/047d8942-105b-11e6-9f7a-601f8dfb1269.png)

I use gulp to inject, but we can see in the index.html in dist folder the import succeed:
![image](https://cloud.githubusercontent.com/assets/3800025/14951686/3452dd34-105b-11e6-812f-92452ab1bffd.png)

Then I import CookieService in my app.component.ts:
![image](https://cloud.githubusercontent.com/assets/3800025/14951698/4c056ac8-105b-11e6-8a71-24ec075fc8aa.png)

And use the service as a provider: 
![image](https://cloud.githubusercontent.com/assets/3800025/14951706/6d1b9778-105b-11e6-9920-624471d3e987.png)

I add ANGULAR2_COOKIE_PROVIDERS into main.ts
![image](https://cloud.githubusercontent.com/assets/3800025/14952024/3473e694-105d-11e6-8a2c-0918d1a1645e.png)

And I have finally:
![image](https://cloud.githubusercontent.com/assets/3800025/14951730/7db082a6-105b-11e6-8408-02a46c742cf1.png)

I really don't understand .. I think the problem come from me but I don't understand what's happening.

**Comment by salemdar** [comment]
Hey @NablaT 
First of all, you don't need to add anything related to _angular2-cookie_ to your `bootstrap()` function in the `main.ts` file, unless you want to change default cookie options. 
What are you using to serve js files? Gulp-connect? Maybe you should check the options for that. If you could provide me a repository link, I could try to help.

**Comment by NablaT** [comment]
Hey @salemdar 
I removed everything related to angular2-cookie in my bootstrap().
And the angular2-cookie import seems to work because in the folder dist (which contains all files read by the browser), I find in the index.html the correct import. 

Sorry I can't share my repository because it's restricted. However, you could find my config for gulp and the tasks in the following page: https://github.com/NablaT/angular2gen/tree/master/app/templates/gulp

Thank you for your help

**Comment by salemdar** [comment]
@NablaT 
After some experiments, I found out that you have to modify you SystemJS config to solve the problem:

``` javascript
System.config({
    defaultJSExtensions: true,
    "paths": {
        "angular2-cookie/*": "node_modules/angular2-cookie/*"
    },
    packages: {
        "angular2": {
            "defaultExtension": false
        },
        "rxjs": {
            "defaultExtension": false
        },
    }
});
```

I tested the library with angular2-seed project and there wasn't such a problem. But their configuration is different. You can compare your generator's SystemJS and gulp configurations with theirs and find out the source of the problem. I also might look into that when I have more time.

**Comment by NablaT** [comment]
In fact the problem comes from my generator. 
Thanks for your help ;)

**Comment by salemdar** [comment]
No problem, glad to help :).
I updated the readme of the repository. Check the getting started part for newer angular versions.
