### ISSUE TITLE
Parameters for putting are not working

### ISSUE THREAD

**Issue by bard10** [salemdar/angular2-cookies#30]
When i try to put cookie with CookieOptionArgs like this:
`
let token: string = 'blahblahblah';

let cookieConfig: CookieOptionsArgs = {
	path: null,
	domain: null,
	expires: null,
	secure: true
};

cookieService.put('accessToken', token, cookieConfig);;
`
the function doesn't work (the cookie is not added) but without providing optional parameters the function works perfectly fine.

**Comment by alanhe421** [comment]
I met the same problem

**Comment by salemdar** [comment]
Actually it is working as expected :). You are just overwriting defaults with invalid values. For example, try with this:

```typescript
let key = 'testCookieKey';
let value = 'testCookieValue';
let opts: CookieOptionsArgs = {
  expires: new Date('2030-07-19')
};
cookieService.put(key, value, opts);
```

**Comment by Spawnrad** [comment]
I have the same issue, without optional its working.
