### ISSUE TITLE
Update to angular-2.0.0-rc.1

### ISSUE THREAD

**Issue by salemdar** [salemdar/angular2-cookies#4]
Angular version and related dependencies should be updated.

**Comment by capi** [comment]
And there's already `angular-2.0.0-rc.1` out :-)

**Comment by salemdar** [comment]
@capi 
Yeah, they are fast :). But switching from rc0 to rc1 should not be as problematic as switching from beta to rc. 
I updated the ticket though :)

**Comment by salemdar** [comment]
Implemented with the 1.2.0 version.
