### ISSUE TITLE
Unsupported URL Type: npm:angular2-cookie

### ISSUE THREAD

**Issue by phil123456** [salemdar/angular2-cookies#49]
Hi,

I get the above error doing "npm install"

package.json:

```
...
"dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",

    "angular-in-memory-web-api": "~0.2.4",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "zone.js": "^0.7.4",

    "angular2-cookie": "npm:angular2-cookie"
  },

```

I replaced "npm:angular2-cookie" with 1.2.4 and it works
so I dont understand why "npm:angular2-cookie" does not work

**Comment by phil123456** [comment]
I ireplaced the version with 1.2.4 and it works
so I dont understand why "npm:angular2-cookie" does not work

**Comment by phil123456** [comment]
anyone ?

**Comment by phil123456** [comment]
man, the support for this library s..

**Comment by salemdar** [comment]
You already have your solution. Just use version numbers as you have figured out.

**Comment by phil123456** [comment]
just by curiosity I'd wanted to know

**Comment by phil123456** [comment]
modified the wrong file, that line shoult be in systemjs config, not package.json
