### ISSUE TITLE
Remove dependecies to angular components that are not used by angular2-cookies

### ISSUE THREAD

**Issue by leon** [salemdar/angular2-cookies#5]
Hi!

When using angular2-cookie with RC.1 I'm getting that angular2-cookies depends on `@angular/router-deprecated` which is a problem, because I'm using the new router `@angular/router`.

As I can make out from the source, it would suffice with

```
@angular/core
@angular/common
@angular/platform-browser
```

If you need the other dependencies for testing move them to `devDependencies`

**Comment by salemdar** [comment]
Hey @leon 
Thanks for pointing that out. I will check and remove unneeded dependencies.

**Comment by salemdar** [comment]
Fixed with the v1.2.1.
