### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by closca** [salemdar/angular2-cookies#58]
```
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.

```
I think should update the dependencies to ^4.0.0

**Comment by stphane** [comment]
Same issue here, I might concider using [ngx-cookie-service](https://www.npmjs.com/package/ngx-cookie-service) instead.

**Comment by salemdar** [comment]
Angular2-cookie is dead. Please use [ngx-cookie](https://github.com/salemdar/ngx-cookie). It is literally written in the repo readme with big punto letters.
