### ISSUE TITLE
Make CookieOption parameters optional

### ISSUE THREAD

**Issue by digital216** [salemdar/angular2-cookies#6]
I only need to set an expiration on the cookies I'm going to set in my app, but I have to specify something for every option if I'm going to set the expiration.  Or am I missing something?

**Comment by salemdar** [comment]
Hey @digital216 
No, you are not missing anything. That is a design flaw which I will fix in the next release. Thanks for pointing that out.

**Comment by salemdar** [comment]
Fixed with the v1.2.1.
