### ISSUE TITLE
Does supplying cookie options need to be so complex?

### ISSUE THREAD

**Issue by stewhouston** [salemdar/angular2-cookies#7]
You're obviously smarter than me so I may be missing something. Have I done this in the way that was intended?

```
let expiresTimestamp = (new Date).setFullYear(2025);

class MyCookieOpts implements CookieOptionsArgs {
    path = '/';
    domain = 'localhost';
    expires = new Date(expiresTimestamp);
    secure = false;
}

this.cookieService.put('key', 'value', new CookieOptions(new MyCookieOpts));
```

If so, is this really necessary? The learning curve for TypeScript/Angular2 is already high enough...

**Comment by salemdar** [comment]
Hey @stewhouston 
Actually, you can do the following:

``` typescript
let expires:Date = new Date();
expires.setFullYear(2025);

let options: CookieOptionsArgs = <CookieOptionsArgs> {
        expires: expiresTimestamp
    };

this.cookieService.put('key', 'value', options);
```

But if you want to override defaults options, check the last part of the readme file.

**Comment by stewhouston** [comment]
Thanks mate, that's much cleaner. As Angular2 gets more popular the repo might pick up steam. There will probably be a few more jQuery-for-everything converts like me coming by. This snippet would be very helpful in the readme.
