### ISSUE TITLE
Not able get cookies value in other component 

### ISSUE THREAD

**Issue by DannyGolhar** [salemdar/angular2-cookies#9]
@salemdar 
Did following steps:

1 . import { CookieService } from 'angular2-cookie/core';
1. constructor(private _cookieService:CookieService){
   }
2. let data=this._cookieService.getObject('keyName');

but data is not coming.
Thanks in advance.

**Comment by salemdar** [comment]
Hey Danny,

We need more than that. Which angular version are you using and how is your SystemJS configuration?
